# Generated by Django 2.2.24 on 2022-06-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamic',
            options={'verbose_name': '歌曲动态', 'verbose_name_plural': '歌曲动态'},
        ),
    ]
